server:
  port: 8088
  servlet:
    context-path: /
  #设置头的大小
  max-http-header-size: 102400
# 引入 数据库的相关配置
spring:
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: >
      jdbc:mysql://localhost:3306/stock?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      &allowMultiQueries=true
    username: fund
    password: fund
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置Redis的使用
  redis:
    database: 8 # 所使用的数据库  默认是0
    host: 127.0.0.1  #所使用的redis的主机地址
    port: 6379  # 端口号  默认是 6379
    password:  # 密码
    timeout: 5000 # 超时时间  5000毫秒
    # 连接池 lettuce 的配置
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-wait: 100000
  # 配置thymeleaf的相关信息
  thymeleaf:
    # 开启视图解析
    enabled: true
    #编码格式
    encoding: UTF-8
    #前缀配置
    prefix: classpath:/templates/
    # 后缀配置
    suffix: .html
    #是否使用缓存 开发环境时不设置缓存
    cache: false
    # 格式为 HTML 格式
    mode: HTML5
    # 配置类型
    servlet:
      content-type: text/html
#整合mybatis时使用的。   去掉整合 MyBatis的配置信息
mybatis-plus:
  # 配置 mapper文件的位置
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #  配置数据库表的列别名设置
  global-config:
    db-config:
      table-underline: true # 驼峰方式转换
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#配置日志文件
logging:
  config: classpath:log4j2spring.xml
#配置访问stock的地址信息
restUrl:
  crawlerUrl: http://localhost:8082/Crawler/stock/
mylog:
  exc-full-show: false
  run-time: 0
  result-length: 500
#xxl-job-admin 的相关配置信息
XXL_JOB_IP: 127.0.0.1
XXL_JOB_PORT: 8091
xxl:
  job:
    admin:
      addresses: http://${XXL_JOB_IP}:${XXL_JOB_PORT}/xxl-job-admin
      username: admin
      password: 123456
    executor:
      appname: xxl-job-executor-strategy
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 1
      ip:
    accessToken:
strategy:
  job:
    add:
      url: http://${XXL_JOB_IP}:${XXL_JOB_PORT}/xxl-job-admin/jobinfo/add
    update:
      url: http://${XXL_JOB_IP}:${XXL_JOB_PORT}/xxl-job-admin/jobinfo/update
    remove:
      url: http://${XXL_JOB_IP}:${XXL_JOB_PORT}/xxl-job-admin/jobinfo/remove
    enable:
      url: http://${XXL_JOB_IP}:${XXL_JOB_PORT}/xxl-job-admin/jobinfo/start
    disable:
      url: http://${XXL_JOB_IP}:${XXL_JOB_PORT}/xxl-job-admin/jobinfo/stop